{
    "name": "Real Estate",
    "version": "17.0.1.0.1",
    "summary": "Real Estate For Teaching",
    "category": "Dev/Teaching",
    'license': 'LGPL-3',
    "application": True,
    "support": "hspring0077@gmail.com",
    "author": "hspring",
    "website": "https://yeada.tech",
    "images": ["static/description/banner.jpg"],
    "data": [
        "security/ir.model.access.csv",        
        "views/estate_property_type.xml",
        "views/estate_property_tag.xml",
        "views/estate_property_offer.xml",
        "views/estate_property.xml",
        "views/menus.xml",
    ],
}
